#!/usr/bin/env ruby
puts "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n"
puts "<html><body style='color: red'>HELLO RUBY WORLD - Request Method - #{ENV.inspect} </body></html>\r\n"